canonical: https://www.medizininformatik-initiative.de/fhir/core/modul-labor
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
status: active
version: 2025.0.0
id: mii-ig-labor-de-2025
name: MII_IG_Labor_DE
packageId: de.medizininformatikinitiative.kerndatensatz.labor
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  hl7.fhir.uv.ips: 1.0.0
  de.medizininformatikinitiative.kerndatensatz.meta: 2025.0.0-alpha1
