canonical: https://www.medizininformatik-initiative.de/fhir/core/modul-labor
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
status: active
version: 2025.0.2
dependencies:
  hl7.fhir.uv.ips: 1.1.0
  de.medizininformatikinitiative.kerndatensatz.meta: 2025.0.0