id: mii-ig-labor
canonical: https://www.medizininformatik-initiative.de/fhir/core/modul-labor
name: MII_IG_Labor
title: "MII IG Modul Laborbefund"
description: "Implementierungsleitfaden des Moduls 'Laborbefund' für den Kerndatensatz der Medizininformatik-Initiative"
status: active
version: 2026.0.0
packageId: de.medizininformatikinitiative.kerndatensatz.labor
fhirVersion: 4.0.1
applyExtensionMetadataToRoot: false
copyrightYear: 2019+
releaseLabel: Release
license: CC-BY-4.0
jurisdiction: urn:iso:std:iso:3166#DE "Germany"
publisher:
  name: Medizininformatik-Initiative
  url: https://www.medizininformatik-initiative.de

dependencies:
  hl7.fhir.uv.ips: 2.0.0
  de.medizininformatikinitiative.kerndatensatz.meta: 2026.0.0
  de.basisprofil.r4: 1.5.x

pages:
  index.md:
    title: Start
  beschreibung-modul.md:
    title: Beschreibung Modul
    zeitpunkte-im-labor.md:
      title: Zeitpunkte im Labor
  kontext.md:
    title: Kontext im Gesamtprojekt
  anwendungsfaelle.md:
    title: Anwendungsfälle / Informationsmodell
    szenarien.md:
      title: Beschreibung von Szenarien
    datensaetze.md:
      title: Datensätze inkl. Beschreibungen
    uml.md:
      title: UML
  technische-implementierung.md:
    title: Technische Implementierung
    fhir-profile.md:
      title: FHIR-Profile
    extensions.md:
      title: Extensions
    terminologien.md:
      title: Terminologien
    capability-statement.md:
      title: CapabilityStatement
    conformance.md:
      title: Konformität
    specimen.md:
      title: Specimen (Modul Biobank)
  referenzen.md:
    title: Referenzen
  release-notes.md:
    title: Release Notes

menu:
  Start: index.html
  Beschreibung:
    Beschreibung Modul: beschreibung-modul.html
    Zeitpunkte im Labor: zeitpunkte-im-labor.html
    Kontext im Gesamtprojekt: kontext.html
  Anwendungsfälle:
    Übersicht: anwendungsfaelle.html
    Szenarien: szenarien.html
    Datensätze inkl. Beschreibungen: datensaetze.html
    UML: uml.html
  Technische Implementierung:
    Übersicht: technische-implementierung.html
    FHIR-Profile: fhir-profile.html
    Extensions: extensions.html
    Terminologien: terminologien.html
    CapabilityStatement: capability-statement.html
    Konformität: conformance.html
    Specimen (Modul Biobank): specimen.html
  Artefakte: artifacts.html
  Referenzen: referenzen.html
  Release Notes: release-notes.html

parameters:
  path-pages:
    - input/intro-notes
  i18n-default-lang: de
  i18n-lang:
    - en
  translation-sources:
    - input/translations/en
  excludexml: false
  excludejson: false
  excludettl: true
  special-url:
    - https://www.medizininformatik-initiative.de/fhir/core/modul-labor/CapabilityStatement/metadata

instanceOptions:
  manualSliceOrdering: true
